title: Blog
description: Bienvenido a mi espacio web personal
author: Joan Cano
github: https://github.com/JoanCano
about: Geógrafo especializado en GIS y Teledetección. Geoinquieto.
disqus_shortname: jcano
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/joan.canoaladid"
    - icon: fa-twitter
      link: "https://twitter.com/Joan_C_A"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/joan-cano-aladid-122835b4/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/JoanCano"

share:
  twitter_username: Joan_C_A
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://joancano.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
